name: Deploy to Netlify

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          npm i -g netlify-cli
          netlify deploy --prod --no-build --dir "./build" --site "ee0d2da1-a242-4db8-bf08-8dc2ae7c9e3f"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
